reqiure(['config'],function(){
    require(['common'],function(){
        $('.btn').click(function(){
            $.post('http://localhost:88/login',{username:$('#username').val(),password:$('#password').val()},function(){
                console.log(res);
                if(res.status){
                    window.location.href='index.html';
                    window.localStorage.setItem('token',res.data);
                }
                else{
                    window.alert(res.message);
                }
            })
        })
    });
});